version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: foodingre_app
    ports:
      - "60080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=Asia/Tokyo
    container_name: foodingre_db
    ports:
      - "63306:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/mysql_data:/var/lib/mysql
    env_file:
      - ./docker/db/db_key.env